### ISSUE TITLE
PDQ creates ; separated CSV

### ISSUE THREAD

**Issue by SmartHomeFanatic** [jlukenichols/KUDellWarrantyChecker#2]
Hi there!

First of all thanks for that awesome work! That thing saves me a lot of time.
As I implemented the script I realized that PDQ saves the CSV separated by ; as this is the standard here in Germany.

Unfortunately I cannot convice PDQ to change this. Is there any chance that the script can also read CSV files that contain ; instead of ,? I'd like to automate the process without the need of replacing the ; in the csv before the import.

Thanks! Much appreciate!

**Comment by jlukenichols** [comment]
Hello,

I just pushed a commit that should allow for the feature you are asking for. It also fixes a bug with the log file names being broken which I didn't notice until I looked into your issue.

There is now a config option in DefaultSettings.ps1 that allows you to change the delimiter of the input file:

```
#Define the delimiter used in the input CSV
$InputCSVDelimiter = ","
```

You should duplicate this line into your CustomSettings.ps1 file and then change it from a comma to a semicolon. This is tested and confirmed working in my environment but I am using American localization so please test and let me know if it works with German localization.

Please note that there is a second CSV file that is generated during the running of the script (DellWarrantyData.CSV) that is still hard-coded to utilize commas. I intended to make this a configuration option as well but I discovered that using the command line option for PDQ Inventory to import custom field data there is no argument to pass it the delimiter character, it just assumes comma. Hopefully that will work the same way in your environment because there's not much I can do about that.

**Comment by SmartHomeFanatic** [comment]
Hi!

That's wonderful! Will test this tomorrow.

Import into PDQ worked without an issue with the file that your script created. So no worries about that (unless you want to change this anyways).

**Comment by SmartHomeFanatic** [comment]
Hi!

Me again. This is working great for me now.
I already automated the process so that I have the current values on hand without doing anything.

Thanks! That is saving me so much time!
