### ISSUE TITLE
Missing or duplicate parameters

### ISSUE THREAD

**Issue by MatAnzPL** [jlukenichols/KUDellWarrantyChecker#4]
Importing settings from DefaultSettings.ps1
FullPathToInputCSV: C:\KUDellWarrantyChecker-main\ExampleInput.CSV
Checking if $TokenExpiration  is less than 04/04/2022 15:03:06
Generating new auth token...
Invoke-WebRequest: C:\KUDellWarrantyChecker-main\KUDellWarrantyChecker.ps1:79
Line |
  79 |  …     $Auth = Invoke-WebRequest "$($requestAccessTokenUri)?client_id=$( …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {   "error":"invalid_request",   "error_description":"Missing or duplicate parameters" }

**Comment by jlukenichols** [comment]
MatAnzPL,

Please note the comments at the top of the DefaultSettings.ps1 file:

#DO NOT MODIFY THIS FILE. 
#Create your own CustomSettings.ps1 file by duplicating this file and renaming it.
#If CustomSettings.ps1 exists then it will be read instead of this file.
#If you modify this file instead of creating a CustomSettings.ps1 file it will overwrite your configuration when you pull a new version from GitHub.

Additionally, it looks like you do not have a valid Dell API key and secret. Please note the comment next to those variables:

#Define your Dell warranty API key. This will be the "client_id" when you generate your token.
$DellWarrantyAPIKey = "" # Get your own from Dell TechDirect https://techdirect.dell.com/Portal/APIs.aspx If you run into issues email APIs_TechDirect@dell.com

#Define your Dell warranty API key secret. This will be the "client_secret" when you generate your token.
$DellWarrantyAPIKeySecret = "" # Get your own from Dell TechDirect https://techdirect.dell.com/Portal/APIs.aspx If you run into issues email APIs_TechDirect@dell.com
